# env:
  # TERM: alacritty

window:
  dynamic_title: true
  opacity: 0.8
  padding:
    x: 2
    y: 2

mouse:
    hide_when_typing: true

scrolling:
  history: 10000
  multiplier: 10

font:
  # family: "FiraCode Nerd Font"
  normal:
    family: "JetBrainsMono Nerd Font"
    style: regular 
  bold:
    family: "JetBrainsMono Nerd Font"
    style: semibold 
  italic:
    family: "JetBrainsMono Nerd Font"
    style: italic  
  size: 18 

  # draw_bold_text_with_bright_colors: true

# colors:
  # primary:
  #   background: "#1E1E2E" # base
  #   foreground: "#CDD6F4" # text
  #     # Bright and dim foreground colors
  #   dim_foreground: "#CDD6F4" # text
  #   bright_foreground: "#CDD6F4" # text

#     # Cursor colors
#     cursor:
#       text: "#1E1E2E" # base
#       cursor: "#F5E0DC" # rosewater
#     vi_mode_cursor:
#       text: "#1E1E2E" # base
#       cursor: "#B4BEFE" # lavender

#     # Search colors
#     search:
#       matches:
#         foreground: "#1E1E2E" # base
#         background: "#A6ADC8" # subtext0
#       focused_match:
#         foreground: "#1E1E2E" # base
#         background: "#A6E3A1" # green
#       footer_bar:
#         foreground: "#1E1E2E" # base
#         background: "#A6ADC8" # subtext0

#     # Keyboard regex hints
#     hints:
#       start:
#         foreground: "#1E1E2E" # base
#         background: "#F9E2AF" # yellow
#       end:
#         foreground: "#1E1E2E" # base
#         background: "#A6ADC8" # subtext0

#     # Selection colors
#     selection:
#       text: "#1E1E2E" # base
#       background: "#F5E0DC" # rosewater
    # normal:
    #   black: "#4C566A"
    #   red: "#bf616a"
    #   green: "#A3BE8C"
    #   yellow: "#D7BA7D"
    #   blue: "#5e81ac"
    #   magenta: "#B48EAD"
    #   cyan: "#88c0d0"
    #   white: "#abb2bf"

    #   # Bright colors
    # bright:
    #   black: "#4C566A"
    #   red: "#bf616a"
    #   green: "#A3BE8C"
    #   yellow: "#D7BA7D"
    #   blue: "#5e81ac"
    #   magenta: "#B48EAD"
    #   cyan: "#88c0d0"
    #   white: "#abb2bf"
    # Normal colors
    # normal:
    #   black: "#45475A" # surface1
    #   red: "#F38BA8" # red
    #   green: "#A6E3A1" # green
    #   yellow: "#F9E2AF" # yellow
    #   blue: "#89B4FA" # blue
    #   magenta: "#F5C2E7" # pink
    #   cyan: "#94E2D5" # teal
    #   white: "#BAC2DE" # subtext1

    # # Bright colors
    # bright:
    #   black: "#585B70" # surface2
    #   red: "#F38BA8" # red
    #   green: "#A6E3A1" # green
    #   yellow: "#F9E2AF" # yellow
    #   blue: "#89B4FA" # blue
    #   magenta: "#F5C2E7" # pink
    #   cyan: "#94E2D5" # teal
    #   white: "#A6ADC8" # subtext0

    # dim:
    #   black: "#45475A" # surface1
    #   red: "#F38BA8" # red
    #   green: "#A6E3A1" # green
    #   yellow: "#F9E2AF" # yellow
    #   blue: "#89B4FA" # blue
    #   magenta: "#F5C2E7" # pink
    #   cyan: "#94E2D5" # teal
    #   white: "#BAC2DE" # subtext1
    # indexed_colors:
    #     - { index: 16, color: "#FAB387" }
    #     - { index: 17, color: "#F5E0DC" }

selection:
  save_to_clipboard: true 

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }

cursor:
  style: Underline
  unfocused_hollow: true
  vi_mode_style: Block
