# Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

# Unbinding
unbind C-y
unbind &
unbind q

# Settings
set -g prefix C-y
bind C-y send-prefix

bind q kill-pane

# Options
set -g history-limit 5000
set -g renumber-windows on

# Splits
bind s split-window -v
bind v split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

