# Font
font_family Symbols Nerd Font # JetBrainsMono Nerd Font
font_size 24.0
disable_ligatures always

# Theme
# include ./Afterglow.conf
# include ./rose-pine-moon.conf
include ./rose-pine.conf
# background_opacity 0.85

# Cursor
cursor #8fee96
mouse_hide_wait -1

term xterm-256color
